config/routes.rb
Rails.application.routes.draw do

  # #CRUD

  # #READ

  # #read all of the restaurant
  # get '/restaurants', to: "restaurants#index"

  # #read one restaurant
  # # restaurants/158 -> Restaurant.find(158)
  # get '/restaurants/:id', to: "restaurants#show"

  # #CREATE

  # #1st get the blank form
  # get '/restaurants/new', to: "restaurants#new"

  # #2nd save the form to the db
  # post '/restaurants', to: "restaurants#create"

  # #UPDATE

  # #1st get the restaurant form
  # # restaurants/158/edit
  # get '/restaurants/:id/edit', to: "restaurants#edit"

  # #2nd send the info to the database
  # # restaurants/158
  # patch '/restaurants/:id', to: "restaurants#update"

  # #DESTROY
  # # restaurants/158
  # delete '/restaurants/:id', to: "restaurants#destroy"

  resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  validates :rating, inclusion: { in: [1,2,3,4,5]}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show

    # http://localhost:3000/restaurants/5
  end


  def new
    # get a blank restaurant record
    @restaurant = Restaurant.new
  end

  def create
    # @restaurant = Restaurant.new(name: params[:name], address: params[:address], rating: params[:rating])
    # new record with values from form
    @restaurant = Restaurant.new(restaurant_params)

    #save record
    @restaurant.save

    #redirect to another page
    redirect_to restaurant_path(@restaurant)

  end

  def edit
    # form with restaurant info filled out
    # @restaurant = Restaurant.find(params[:id])
  end


  def update
    @restaurant.update(restaurant_params)
    # redirect to the show page
    redirect_to @restaurant
  end


  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    # params[:restaurant] => { name: params[:name].... }
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def edit_restaurant_params
    params.require(:restaurant).permit(:rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%#= form_for(restaurant) do |f| %>
  <%#= f.label :name, "Enter the name" %>
  <%#= f.text_field :name %>
  <%#= f.label :address %>
  <%#= f.text_field :address %>
  <%#= f.label :rating %>
  <%#= f.text_field :rating %>
  <%#= f.submit %>
  <%# end %>
  <%= simple_form_for restaurant  do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>
<!--  patch '/restaurants/:id', to: "restaurants#update"
 -->
<!-- <form action="/restaurants/6" method="PATCH">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="restaurant[name]" placeholder="enter a name" value="joe exotic">
  <input type="text" name="restaurant[address]" placeholder="enter a address" value="shanghai">
  <input type="text" name="restaurant[rating]" placeholder="enter a rating" value="4">
  <input type="submit">
</form> -->
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<% @restaurants.each do |restaurant| %>
  <!-- link_to "ANCHOR", path -->
  <h4><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h4>
  <p><%= restaurant.address %></p>
  <p><%= link_to "Destroy this restaurant", restaurant_path(restaurant.id), data: {confirm: "Are you sure?" }, method: :delete %></p>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>
<!-- post '/restaurants', to: "restaurants#create" -->
<!-- <form action="/restaurants" method="POST">
  <%#= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="restaurant[name]" placeholder="enter a name">
  <input type="text" name="restaurant[address]" placeholder="enter a address">
  <input type="text" name="restaurant[rating]" placeholder="enter a rating">
  <input type="submit">
</form> -->
<!-- params: {
restaurant: {
name: "Shake Shack", 
address: "Shanghai", 
rating: 3
}
} -->
<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<%= link_to "Back", restaurants_path %> | <%= link_to "Edit", edit_restaurant_path(@restaurant) %>